services:
  - type: web
    name: dad-magic-socket-server
    env: node
    plan: free
    buildCommand: echo "No build needed" && echo "Node version:" && node --version
    startCommand: node ultra-simple.js
    rootDir: render-server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
